### ISSUE TITLE
Build script access environment at compile time instead of at build time

### ISSUE THREAD

**Issue by redsun82** [rust-lang/rustc_apfloat#22]
The build script uses `env!("CARGO_PKG_VERSION")`, relying on that variable being set by `cargo` when the build script is compiled. However, the [docs](https://doc.rust-lang.org/cargo/reference/build-scripts.html#inputs-to-the-build-script) state that inputs to the build script are passed at run time (of the build script):

> _When the build script is run_, there are a number of inputs to the build script, all passed in the form of environment variables.

(emphasis mine)

In particular, that is for example what the [bazel wrapper](https://github.com/bazelbuild/rules_rust) around rust rules expects, so that any crate depending on this one will fail to build with bazel.

**Comment by redsun82** [comment]
Some time ago I've opened https://github.com/rust-lang/rustc_apfloat/pull/17. I'm currently using that as a workaround, adding to our `Cargo.toml` (that is used as a base for generating the bazel build configuration) this snippet:

```toml
[patch.crates-io]
# patch for build script bug preventing bazel build
# see https://github.com/rust-lang/rustc_apfloat/pull/17
rustc_apfloat = { git = "https://github.com/redsun82/rustc_apfloat.git", rev = "32968f16ef1b082243f9bf43a3fbd65c381b3e27" }
```
